services:
    postgres:
        container_name: postgres
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test
            
        ports:
            - '5432:5432'
        volumes:
          - postgres:/var/lib/postgresql/data

    backend:
        container_name: backend
        image: hemanth12reddy/springboot-backend:${backend_image_tag:-latest}
        restart: always
        ports:
            - '9001:9001'
        depends_on:
            - postgres
        # env_file:
        #     - .env.backend
        environment:
            - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
            - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

    frontend:
        container_name: frontend
        image: hemanth12reddy/springboot-backend:${frontend_image_tag:-latest}
        restart: always
        ports:
            - '3000:80'
        depends_on:
            - backend

volumes:
   postgres: 
