name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push backend image
        run: | 
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/springboot-backend:${{ github.ref_name }}-${{ github.sha }}-${{ github.run_number }} .
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/springboot-backend:${{ github.ref_name }}-${{ github.sha }}-${{ github.run_number }}

      - name: build and push frontend image
        run: | 
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/springboot-frontend:${{ github.ref_name }}-${{ github.sha }}-${{ github.run_number }} .
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/springboot-frontend:${{ github.ref_name }}-${{ github.sha }}-${{ github.run_number }}
        working-directory: frontend
      
      - name: update image tag
        run: |
          sed -i 's/^backend_image_tag=.*/backend_image_tag="${{ github.ref_name }}-${{ github.sha }}-${{ github.run_number }}"/' .env
          echo "Updated backend_image_tag to: ${{ github.ref_name }}-${{ github.sha }}-${{ github.run_number }}"

          sed -i 's/^frontend_image_tag=.*/frontend_image_tag="${{ github.ref_name }}-${{ github.sha }}-${{ github.run_number }}"/' .env
          echo "Updated frontend_image_tag to: ${{ github.ref_name }}-${{ github.sha }}-${{ github.run_number }}"

      - name: commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .env
          git commit -m "Update image tags in .env"
          git push origin main

  deploy:
    name: Deploy in docker compose
    runs-on: [beehyv-test]
    needs: build
    steps:
      - name: check docker version
        run: docker version

      - name: checkout to working directory
        run: | 
          cd ${{ secrets.ENV_SETUP_PATH }}
          cd springboot-react
          git pull origin main
      
      - name: deploy application
        run: |
          source .env
          docker compose up -d
